// Prompt Archive : Bestiary - species attire data and compatibility rules
// Natural dyes and mineral pigments. Values double as CSS colors for the preview chips.
const outfitColors=["white","black","brown","green","blue","red","purple","gold","gray","teal"];

const styles = {
  beast:{name:"beastfolk clothing",sp:"beastfolk",body:["furred body", "animal snout", "digitigrade legs", "paw-like hands"],sil:["fur trimmed layered silhouette","loose wrapped silhouette","compact hunter silhouette","broad shouldered pelt silhouette"],
    tops:["fur trimmed hide vest","wrapped hide tunic","strapped pelt jacket","short fur mantle","laced hide bodice","sleeveless hunter top"],
    bottoms:["hide wrap skirt","fringed hide trousers","short pelt skirt","strapped hide shorts","layered fur leggings","tied hide trousers"],
    shoes:["wrapped hide boots","fur cuffed boots","laced hunter sandals","soft padded boots"],
    extras:["tail opening at the waist","claw bead necklace","fur shoulder trim","braided leather cords","tooth pendant","wrapped forearm hide","hanging fur tassels","bone toggle fastenings"]},
  kitsune:{name:"fox spirit clothing",sp:"fox spirit",body:["slit pupils", "fur trimmed forearms", "fox-like features"],sil:["long trailing silhouette","layered ceremonial silhouette","slim wrapped silhouette","wide sleeved silhouette"],
    tops:["wide sleeved shrine robe","layered ceremonial haori","wrapped ritual top","short shrine jacket","banded ceremonial bodice","open ritual mantle"],
    bottoms:["long pleated ritual skirt","wide ceremonial trousers","layered wrap skirt","short shrine skirt","banded ritual trousers","trailing hem skirt"],
    shoes:["raised wooden sandals","tabi split-toe boots","woven straw sandals","laced ritual sandals"],
    extras:["paper charm slips","braided rope belt","bell on a cord","folded paper strips","vermilion trim","tasselled sash ends","carved wooden beads","wide obi sash"]},
  draco:{name:"dragon-blooded clothing",sp:"dragon-blooded",body:["scaled skin", "clawed hands", "slit pupils", "ridged brow"],sil:["plated angular silhouette","heavy scaled silhouette","sharp ridged silhouette","broad armored silhouette"],
    tops:["scale plated bodice","ridged shoulder mantle","layered scale jacket","hooked clasp breastplate","banded scale vest","high collar scale top"],
    bottoms:["plated scale skirt","ridged scale trousers","layered plate skirt","banded scale leggings","split plate skirt","strapped scale shorts"],
    shoes:["clawed plate boots","ridged tall boots","banded scale boots","heavy talon boots"],
    extras:["overlapping scale trim","hooked metal clasps","ridged spine plates","gemstone inlay","horn tip caps","chain draped shoulder","clawed gauntlet cuffs","scaled collar guard"]},
  demon:{name:"demon clothing",sp:"demon",body:["grey skin", "clawed hands", "pointed ears", "dark sclera"],sil:["sharp asymmetric silhouette","narrow high-collar silhouette","clawed layered silhouette","tapered dark silhouette"],
    tops:["high collar dark coat","asymmetric buckled jacket","clawed shoulder bodice","laced dark bustier","strapped infernal vest","layered dark mantle"],
    bottoms:["asymmetric dark skirt","buckled tight trousers","split hem skirt","strapped dark shorts","layered dark leggings","long slit skirt"],
    shoes:["clawed heeled boots","buckled tall boots","pointed dark boots","spiked ankle boots"],
    extras:["iron ring buckles","chained waist links","clawed cuff tips","brand marked leather","spiked shoulder studs","dark ribbon ties","hanging chain loops","pointed collar tips"]},
  oni:{name:"oni clothing",sp:"oni",body:["red skin", "short tusks", "heavy muscular build"],sil:["one shoulder heavy silhouette","loose draped silhouette","broad bulky silhouette","asymmetric wrapped silhouette"],
    tops:["one shoulder hide wrap","loose open robe","banded chest wrap","layered fur collar top","tied sash bodice","short heavy jacket"],
    bottoms:["tiger pelt wrap skirt","loose wide trousers","short hide wrap","banded heavy trousers","layered wrap skirt","tied waist shorts"],
    shoes:["thick straw sandals","heavy wooden clogs","wrapped cloth boots","banded leather sandals"],
    extras:["thick rope sash","iron ring cuffs","carved gourd on the hip","wide cloth waistband","banded arm wraps","hanging iron rings","tasselled cord","studded leather band"]},
  celestial:{name:"celestial clothing",sp:"celestial being",body:["luminous skin", "gold irises", "marble-smooth skin"],sil:["flowing draped silhouette","tall column silhouette","layered light silhouette","wide shouldered drape silhouette"],
    tops:["draped white robe top","layered ceremonial mantle","banded celestial bodice","high collar drape top","gathered shoulder robe","pleated ceremonial top"],
    bottoms:["long pleated column skirt","draped ceremonial trousers","layered light skirt","banded celestial skirt","gathered drape trousers","trailing pleated skirt"],
    shoes:["strapped gilt sandals","soft draped slippers","banded ceremonial sandals","tall gilt boots"],
    extras:["gilt band trim","layered sheer drape","suspended ring ornaments","engraved shoulder plate","hanging chain drops","pleated shoulder fall","gilded arm bands","gilded belt disc"]},
  undead:{name:"undead clothing",sp:"undead",body:["pallid grey skin", "sunken eyes", "stitched seams on the skin"],sil:["tattered layered silhouette","hollow draped silhouette","bound wrapped silhouette","uneven ragged silhouette"],
    tops:["tattered grave coat","bandage wrapped bodice","frayed burial shirt","layered shroud mantle","bound linen top","moth eaten jacket"],
    bottoms:["tattered long skirt","frayed burial trousers","bandage wrapped leggings","layered shroud skirt","ragged short trousers","uneven torn skirt"],
    shoes:["cracked burial boots","bandage wrapped boots","worn grave shoes","tattered laced boots"],
    extras:["loose bandage ends","dust stained linen","corroded metal clasps","frayed hanging threads","stitched repair seams","hanging grave tags","dulled silver chain","earth stained hem"]},
  spirit:{name:"spirit clothing",sp:"spirit",body:["translucent body", "faintly glowing skin", "weightless form"],sil:["weightless floating silhouette","soft diffuse silhouette","trailing layered silhouette","narrow drifting silhouette"],
    tops:["sheer floating top","layered gauze bodice","drifting veil mantle","soft translucent wrap","banded gauze top","gathered sheer blouse"],
    bottoms:["floating sheer skirt","layered gauze trousers","trailing translucent skirt","banded gauze leggings","drifting long skirt","gathered sheer shorts"],
    shoes:["wrapped ankle cords","soft floating slippers","sheer banded sandals","thin strapped shoes"],
    extras:["drifting fabric ends","faint glowing trim","layered sheer overlays","weightless hem float","pale gradient fabric","suspended small lights","frayed vaporous hem","thin floating ribbons"]},
  mermaid:{name:"sea folk clothing",sp:"sea folk",body:["webbed hands", "gill slits at the neck", "scaled shins", "fin-like forearms"],sil:["flowing wet silhouette","fitted finned silhouette","layered tidal silhouette","smooth streamlined silhouette"],
    tops:["shell fitted bodice","draped net top","finned shoulder mantle","banded coral bodice","wrapped kelp top","layered scale bodice"],
    bottoms:["finned long skirt","draped net skirt","fitted scale leggings","layered tidal skirt","banded coral shorts","flowing wet skirt"],
    shoes:["webbed strap sandals","finned ankle boots","banded shell sandals","soft wrapped sea boots"],
    extras:["pearl strand trim","woven net panels","coral bead clusters","fin edged trim","hanging shell charms","wet clinging fabric","kelp braided cords","iridescent surface"]},
  avian:{name:"bird folk clothing",sp:"bird folk",body:["feathered forearms", "taloned feet", "round bird-like eyes"],sil:["feather layered silhouette","light airy silhouette","wide caped silhouette","tapered plumed silhouette"],
    tops:["feather layered mantle","light plumed jacket","banded feather bodice","wide feather cape top","short plumed vest","wrapped down top"],
    bottoms:["feather trimmed skirt","light tapered trousers","layered plume skirt","banded feather shorts","short plumed skirt","fitted light leggings"],
    shoes:["taloned strap sandals","light banded boots","feather cuffed boots","short plumed shoes"],
    extras:["layered feather trim","hollow bone beads","wind caught cape","banded wrist plumes","light woven straps","feather tipped hem","carved beak clasp","down lined collar"]},
  dryad:{name:"tree spirit clothing",sp:"tree spirit",body:["bark textured skin", "small leaves growing from the skin", "moss along the shoulders"],sil:["overgrown layered silhouette","rooted heavy-hem silhouette","slim vine wrapped silhouette","broad leafed silhouette"],
    tops:["woven vine bodice","layered leaf mantle","bark plated top","wrapped moss tunic","banded bloom bodice","open branch mantle"],
    bottoms:["layered leaf skirt","woven vine trousers","mossy wrap skirt","bark banded leggings","trailing root skirt","gathered petal skirt"],
    shoes:["woven root sandals","moss lined boots","bark banded shoes","vine wrapped sandals"],
    extras:["climbing vine trim","small bloom clusters","bark texture panels","hanging seed pods","moss lined edges","woven twig belt","leaf shaped trim","amber sap beads"]},
  golem:{name:"stone folk clothing",sp:"stone folk",body:["stone skin", "glowing cracks in the skin", "crystal growths on the arms"],sil:["blocky heavy silhouette","angular crystalline silhouette","broad slab silhouette","stiff plated silhouette"],
    tops:["stone plated chest wrap","crystal banded bodice","heavy slab mantle","carved stone collar top","banded ore vest","layered rock plate top"],
    bottoms:["stone plated skirt","heavy carved trousers","crystal banded leggings","layered slab skirt","banded ore shorts","blocky plated trousers"],
    shoes:["heavy stone boots","carved slab sandals","banded ore boots","thick plated shoes"],
    extras:["glowing seam cracks","carved rune grooves","raw crystal shards","hammered metal bands","chipped stone edges","ore vein inlay","heavy iron rivets","dust worn surfaces"]},
  moth:{name:"moth folk clothing",sp:"moth folk",body:["fuzzy collar of fur at the neck", "compound eyes", "fine powder on the skin"],sil:["soft fuzzy silhouette","wide shouldered fuzz silhouette","powdery layered silhouette","rounded plush silhouette"],
    tops:["fuzzy collared mantle","powdered cape top","soft plush bodice","banded velvet top","layered dusty jacket","wide shouldered fuzz top"],
    bottoms:["soft plush skirt","powdered layered skirt","banded velvet trousers","fuzzy trimmed shorts","wide dusty skirt","gathered soft trousers"],
    shoes:["fuzzy cuffed boots","soft velvet shoes","banded plush boots","powdered strap sandals"],
    extras:["dusty powder finish","soft fuzz collar","patterned eye spots","velvet nap texture","muted wing patterning","banded cord ties","soft scalloped trim","dim lantern charm"]},
  slime:{name:"slime folk clothing",sp:"slime folk",body:["translucent gel body", "glossy wet skin", "soft boneless limbs"],sil:["soft rounded silhouette","fluid clinging silhouette","translucent layered silhouette","dripping hem silhouette"],
    tops:["clinging translucent top","layered jelly bodice","soft rounded wrap","banded gel vest","glossy fitted top","dripping hem mantle"],
    bottoms:["clinging translucent skirt","layered jelly shorts","soft rounded skirt","banded gel leggings","glossy fitted trousers","dripping hem skirt"],
    shoes:["glossy soft boots","translucent strap sandals","banded gel shoes","rounded jelly boots"],
    extras:["glossy wet surface","translucent panel inserts","rounded soft edges","suspended bubble specks","dripping trim ends","tinted gradient fabric","smooth seamless finish","soft squashed folds"]},
  elf:{name:"elven clothing",sp:"elf",body:["long pointed ears", "fine sharp features"],sil:["long slender silhouette","tapered layered silhouette","narrow draped silhouette","tall clean-lined silhouette"],
    tops:["long tailored elven coat","layered silk tunic","embroidered fitted bodice","high collar slim jacket","draped shoulder mantle","laced woven top"],
    bottoms:["long slit elven skirt","tapered woven trousers","layered silk skirt","fitted embroidered leggings","draped long skirt","banded slim trousers"],
    shoes:["tall slim elven boots","soft laced boots","banded woven sandals","pointed slim shoes"],
    extras:["fine leaf embroidery","narrow woven belt","layered silk trim","engraved metal clasps","long trailing sash","fine chain accents","subtle gradient dye","carved wood buttons"]}
};

// Secondary species must be listed on both sides. A pairing exists only when the two
// share a habitat, a craft tradition, or a way of dressing a non-human body.
const secondaryCompat = {
  beast:["oni","kitsune","dryad","undead","avian"],
  kitsune:["beast","oni","celestial","spirit","elf"],
  draco:["demon","golem","oni","avian","elf"],
  demon:["draco","undead","oni","golem","moth"],
  oni:["beast","kitsune","draco","demon","golem"],
  celestial:["kitsune","elf","spirit","avian","moth"],
  undead:["beast","demon","spirit","moth","golem"],
  spirit:["kitsune","celestial","undead","moth","slime"],
  mermaid:["dryad","slime","avian","elf"],
  avian:["beast","draco","celestial","moth","mermaid"],
  dryad:["beast","mermaid","elf","moth","slime"],
  golem:["draco","demon","oni","undead","slime"],
  moth:["demon","celestial","undead","spirit","avian","dryad"],
  slime:["spirit","mermaid","dryad","golem"],
  elf:["kitsune","draco","celestial","mermaid","dryad"]
};

// Head features have places on the head. Horns sit on the crown, ears at the sides,
// so a horned beastfolk is a valid roll. `rare: true` marks anything covering the face.
const heroMap = {
  none:{icon:"☆",name:"NO HEAD FEATURE",tag:null,sub:"plain head silhouette",zone:"none",styles:["beast","kitsune","draco","demon","oni","celestial","undead","spirit","mermaid","avian","dryad","golem","moth","slime","elf"]},
  ears:{icon:"🐺",name:"BEAST EARS",tag:"animal ears",sub:"furred ears at the sides",zone:"ears",styles:["beast","kitsune","oni","undead","demon"]},
  longears:{icon:"🌿",name:"LONG EARS",tag:"long pointed ears",sub:"tapered ears at the sides",zone:"ears",styles:["elf","dryad","spirit","celestial","kitsune"]},
  finears:{icon:"🐚",name:"FIN EARS",tag:"fin shaped ears",sub:"webbed ears at the sides",zone:"ears",styles:["mermaid","slime","draco","avian"]},
  horns:{icon:"🐏",name:"CURVED HORNS",tag:"curved horns",sub:"heavy horns on the crown",zone:"crown",styles:["draco","demon","oni","golem","beast"]},
  antlers:{icon:"🦌",name:"ANTLERS",tag:"branching antlers",sub:"forked antlers on the crown",zone:"crown",styles:["dryad","beast","spirit","celestial","elf"]},
  crest:{icon:"🪶",name:"FEATHER CREST",tag:"crest of feathers on the head",sub:"raised plume on the crown",zone:"crown",styles:["avian","celestial","moth"]},
  antennae:{icon:"🦋",name:"ANTENNAE",tag:"feathered antennae",sub:"soft feelers on the crown",zone:"crown",styles:["moth","spirit","slime","dryad"]},
  mask:{icon:"💀",name:"BONE MASK",tag:"bone half mask over the face",sub:"carved bone across the face",zone:"face",rare:true,styles:["undead","oni","golem","demon","spirit"]}
};

// Appendages. `styles` limits which species a RANDOM roll may hand one to, so the
// shuffle never puts a back fin on an elf. Picking one by hand is never restricted:
// a mixed-blood character is a legitimate thing to want.
const backPieces={
  none:{tag:null},
  feather:{tag:"large feathered wings",styles:["celestial","avian","spirit"]},
  bat:{tag:"bat wings",styles:["demon","undead","draco","oni"]},
  insect:{tag:"translucent insect wings",styles:["spirit","dryad","slime"]},
  mothwing:{tag:"broad moth wings",styles:["moth","spirit","dryad"]},
  tail:{tag:"long fluffy tail",styles:["beast","kitsune","oni","demon"]},
  tails:{tag:"many fox tails",styles:["kitsune","spirit"]},
  scaled:{tag:"long scaled tail",styles:["draco","mermaid","demon","oni","golem","slime"]},
  fin:{tag:"finned back crest",styles:["mermaid","slime","draco","avian"]}
};

// Per-item detail tags, appended only at COMPLEXITY Max so details never contradict the garment.
const itemDetails={
  // tops
  "fur trimmed hide vest":["thick fur edging","open unlined front"],
  "wrapped hide tunic":["crossed wrap closure","uneven cut hem"],
  "strapped pelt jacket":["buckled pelt straps","raw suede finish"],
  "short fur mantle":["cropped shoulder cover","hooked front clasp"],
  "laced hide bodice":["front thong lacing","stiff moulded leather"],
  "sleeveless hunter top":["clean armhole cut","stitched side panels"],
  "wide sleeved shrine robe":["long hanging sleeves","crossed front closure"],
  "layered ceremonial haori":["open front panels","stiff woven collar"],
  "wrapped ritual top":["tied side closure","narrow bound waist"],
  "short shrine jacket":["cropped square cut","wide sleeve openings"],
  "banded ceremonial bodice":["stacked fabric bands","bound waist ties"],
  "open ritual mantle":["unfastened open front","printed hem border"],
  "scale plated bodice":["overlapping scale rows","hooked side closure"],
  "ridged shoulder mantle":["raised spine ridges","stiff standing collar"],
  "layered scale jacket":["stacked scale panels","tapered waist seam"],
  "hooked clasp breastplate":["hooked front clasps","shaped chest plating"],
  "banded scale vest":["banded torso rows","open sleeveless cut"],
  "high collar scale top":["tall scaled collar","fitted body seams"],
  "high collar dark coat":["tall stiff collar","long fitted body"],
  "asymmetric buckled jacket":["offset buckle row","uneven front hem"],
  "clawed shoulder bodice":["pointed shoulder tips","boned front seams"],
  "laced dark bustier":["back lacing panel","structured moulded cups"],
  "strapped infernal vest":["crossed strap front","riveted strap ends"],
  "layered dark mantle":["stacked cape layers","pointed hanging tips"],
  "one shoulder hide wrap":["single shoulder cover","knotted side closure"],
  "loose open robe":["unbelted open front","wide fallen sleeves"],
  "banded chest wrap":["wound cloth bands","tucked end finish"],
  "layered fur collar top":["thick fur collar","layered under wrap"],
  "tied sash bodice":["knotted sash front","gathered side folds"],
  "short heavy jacket":["cropped heavy weave","turned back cuffs"],
  "draped white robe top":["fluid draped folds","pinned shoulder clasp"],
  "layered ceremonial mantle":["stacked drape layers","weighted hem edge"],
  "banded celestial bodice":["narrow gilt bands","smooth fitted body"],
  "high collar drape top":["tall shaped collar","falling side drape"],
  "gathered shoulder robe":["gathered shoulder folds","open falling sleeves"],
  "pleated ceremonial top":["fine narrow pleats","banded high waist"],
  "tattered grave coat":["torn ragged hem","missing button gaps"],
  "bandage wrapped bodice":["wound linen strips","loose trailing ends"],
  "frayed burial shirt":["frayed collar edge","stained thin linen"],
  "layered shroud mantle":["overlapping shroud layers","uneven torn edges"],
  "bound linen top":["tightly bound wraps","knotted closure ends"],
  "moth eaten jacket":["small chewed holes","faded worn weave"],
  "sheer floating top":["weightless sheer fabric","lifted hem edges"],
  "layered gauze bodice":["stacked gauze layers","softly blurred seams"],
  "drifting veil mantle":["long drifting veil","unfastened open front"],
  "soft translucent wrap":["see-through soft weave","crossed wrap closure"],
  "banded gauze top":["narrow gauze bands","open shoulder gaps"],
  "gathered sheer blouse":["gathered sheer body","fine rolled hem"],
  "shell fitted bodice":["paired shell cups","knotted cord back"],
  "draped net top":["open woven netting","hanging knot ends"],
  "finned shoulder mantle":["finned shoulder edges","translucent membrane"],
  "banded coral bodice":["branching coral bands","fitted smooth body"],
  "wrapped kelp top":["wound kelp strands","damp clinging fit"],
  "layered scale bodice":["small overlapping scales","iridescent sheen"],
  "feather layered mantle":["stacked feather rows","light open front"],
  "light plumed jacket":["plume trimmed edges","weightless thin shell"],
  "banded feather bodice":["banded feather rows","fitted narrow waist"],
  "wide feather cape top":["wide sweeping cape","clasped front cord"],
  "short plumed vest":["cropped plume body","open sleeveless cut"],
  "wrapped down top":["soft down padding","crossed wrap closure"],
  "woven vine bodice":["interlaced vine weave","open lattice gaps"],
  "layered leaf mantle":["overlapping leaf rows","stem stitched edges"],
  "bark plated top":["rough bark panels","fibrous seam joins"],
  "wrapped moss tunic":["soft moss lining","uneven wrapped hem"],
  "banded bloom bodice":["banded flower rows","fitted smooth body"],
  "open branch mantle":["twisting branch frame","open unfastened front"],
  "stone plated chest wrap":["thick stone slabs","bound cord fastening"],
  "crystal banded bodice":["set crystal bands","fitted carved body"],
  "heavy slab mantle":["broad slab panels","chipped rough edges"],
  "carved stone collar top":["deep carved collar","squared shoulder blocks"],
  "banded ore vest":["banded ore strips","open sleeveless cut"],
  "layered rock plate top":["stacked rock plates","visible mortar seams"],
  "fuzzy collared mantle":["thick fuzz collar","soft open front"],
  "powdered cape top":["fine powder finish","wide falling cape"],
  "soft plush bodice":["deep plush pile","fitted rounded body"],
  "banded velvet top":["banded velvet rows","soft rolled edges"],
  "layered dusty jacket":["muted dusty layers","frayed soft cuffs"],
  "wide shouldered fuzz top":["broad fuzzy shoulders","narrow tapered waist"],
  "clinging translucent top":["clinging wet finish","see-through body"],
  "layered jelly bodice":["stacked jelly layers","rounded soft seams"],
  "soft rounded wrap":["rounded wrap edges","yielding soft fit"],
  "banded gel vest":["banded gel strips","open sleeveless cut"],
  "glossy fitted top":["high gloss surface","seamless fitted body"],
  "dripping hem mantle":["dripping lower edge","glossy open front"],
  "long tailored elven coat":["long clean body","fine tailored seams"],
  "layered silk tunic":["fine silk layers","split side hems"],
  "embroidered fitted bodice":["thread embroidered panels","narrow shaped waist"],
  "high collar slim jacket":["tall narrow collar","close fitted body"],
  "draped shoulder mantle":["falling shoulder drape","clasped front cord"],
  "laced woven top":["fine cord lacing","tight woven weave"],
  // bottoms
  "hide wrap skirt":["overlapped wrap front","raw cut hem"],
  "fringed hide trousers":["side fringe strips","soft suede legs"],
  "short pelt skirt":["thick pelt body","uneven fur hem"],
  "strapped hide shorts":["side strap fastenings","short cut legs"],
  "layered fur leggings":["layered fur bands","tied ankle cords"],
  "tied hide trousers":["knotted waist cord","tapered soft legs"],
  "long pleated ritual skirt":["deep even pleats","stiff woven fabric"],
  "wide ceremonial trousers":["very wide legs","pleated front folds"],
  "layered wrap skirt":["stacked wrap layers","hidden side closure"],
  "short shrine skirt":["short pleated body","banded high waist"],
  "banded ritual trousers":["banded leg segments","tied ankle wraps"],
  "trailing hem skirt":["long trailing back","fine printed border"],
  "plated scale skirt":["overlapping scale plates","hooked waist clasp"],
  "ridged scale trousers":["raised leg ridges","fitted scaled legs"],
  "layered plate skirt":["stacked plate rows","riveted plate edges"],
  "banded scale leggings":["banded scale rows","smooth stretch fit"],
  "split plate skirt":["front split opening","stiff held panels"],
  "strapped scale shorts":["strapped thigh bands","short scaled legs"],
  "asymmetric dark skirt":["angled uneven hem","offset side slit"],
  "buckled tight trousers":["rows of small buckles","close fitted legs"],
  "split hem skirt":["deep front split","pointed hem tips"],
  "strapped dark shorts":["crossed thigh straps","short fitted legs"],
  "layered dark leggings":["layered panel wraps","smooth close fit"],
  "long slit skirt":["high side slit","long falling body"],
  "tiger pelt wrap skirt":["striped pelt body","knotted side closure"],
  "loose wide trousers":["very loose legs","gathered waist cord"],
  "short hide wrap":["short wrapped body","tucked corner fold"],
  "banded heavy trousers":["banded heavy legs","thick woven weave"],
  "tied waist shorts":["knotted waist tie","rolled short legs"],
  "long pleated column skirt":["narrow fine pleats","straight column fall"],
  "draped ceremonial trousers":["draped falling legs","banded high waist"],
  "layered light skirt":["stacked light layers","softly floating hem"],
  "banded celestial skirt":["narrow gilt bands","smooth fitted body"],
  "gathered drape trousers":["gathered side folds","tapered ankle bands"],
  "trailing pleated skirt":["long trailing pleats","weighted hem edge"],
  "tattered long skirt":["torn ragged hem","hanging loose strips"],
  "frayed burial trousers":["frayed leg ends","stained thin weave"],
  "bandage wrapped leggings":["wound linen strips","loose trailing ends"],
  "layered shroud skirt":["overlapping shroud layers","uneven torn edges"],
  "ragged short trousers":["roughly cut legs","split worn seams"],
  "uneven torn skirt":["uneven torn hem","missing fabric gaps"],
  "floating sheer skirt":["weightless lifted hem","see-through layers"],
  "layered gauze trousers":["stacked gauze legs","softly blurred seams"],
  "trailing translucent skirt":["long trailing fall","fine rolled hem"],
  "banded gauze leggings":["narrow gauze bands","smooth close fit"],
  "drifting long skirt":["drifting open hem","weightless soft fall"],
  "gathered sheer shorts":["gathered sheer body","short soft legs"],
  "finned long skirt":["finned side edges","translucent membrane"],
  "draped net skirt":["open woven netting","hanging knot ends"],
  "fitted scale leggings":["small overlapping scales","iridescent sheen"],
  "layered tidal skirt":["stacked flowing layers","damp clinging fall"],
  "banded coral shorts":["branching coral bands","short fitted legs"],
  "flowing wet skirt":["wet clinging fall","fine dripping hem"],
  "feather trimmed skirt":["feather edged hem","light floating body"],
  "light tapered trousers":["weightless thin weave","narrow tapered legs"],
  "layered plume skirt":["stacked plume rows","banded high waist"],
  "banded feather shorts":["banded feather rows","short fitted legs"],
  "short plumed skirt":["short plume body","soft floating hem"],
  "fitted light leggings":["thin close weave","seamless smooth fit"],
  "layered leaf skirt":["overlapping leaf rows","stem stitched edges"],
  "woven vine trousers":["interlaced vine weave","open lattice gaps"],
  "mossy wrap skirt":["soft moss surface","overlapped wrap front"],
  "bark banded leggings":["banded bark strips","fibrous seam joins"],
  "trailing root skirt":["trailing root strands","heavy earthy hem"],
  "gathered petal skirt":["layered petal rows","gathered high waist"],
  "stone plated skirt":["thick stone slabs","bound cord fastening"],
  "heavy carved trousers":["deep carved grooves","broad heavy legs"],
  "crystal banded leggings":["set crystal bands","fitted carved body"],
  "layered slab skirt":["stacked slab rows","chipped rough edges"],
  "banded ore shorts":["banded ore strips","short blocky legs"],
  "blocky plated trousers":["squared plate blocks","visible mortar seams"],
  "soft plush skirt":["deep plush pile","rounded soft hem"],
  "powdered layered skirt":["fine powder finish","stacked soft layers"],
  "banded velvet trousers":["banded velvet rows","soft rolled edges"],
  "fuzzy trimmed shorts":["fuzzy edge trim","short rounded legs"],
  "wide dusty skirt":["wide muted body","frayed soft hem"],
  "gathered soft trousers":["gathered ankle bands","soft brushed weave"],
  "clinging translucent skirt":["clinging wet finish","see-through body"],
  "layered jelly shorts":["stacked jelly layers","rounded soft seams"],
  "soft rounded skirt":["rounded bell shape","yielding soft fall"],
  "banded gel leggings":["banded gel strips","smooth close fit"],
  "glossy fitted trousers":["high gloss surface","seamless fitted legs"],
  "dripping hem skirt":["dripping lower edge","glossy smooth body"],
  "long slit elven skirt":["long side slit","fine tailored seams"],
  "tapered woven trousers":["tight woven weave","narrow tapered legs"],
  "layered silk skirt":["fine silk layers","softly falling hem"],
  "fitted embroidered leggings":["thread embroidered panels","seamless smooth fit"],
  "draped long skirt":["falling draped folds","weighted hem edge"],
  "banded slim trousers":["narrow banded waist","close slim legs"],
  // shoes
  "wrapped hide boots":["wound hide strips","tied shaft cords"],
  "fur cuffed boots":["thick fur cuff","soft padded sole"],
  "laced hunter sandals":["long shin lacing","flat hide sole"],
  "soft padded boots":["quiet padded sole","folded shaft top"],
  "raised wooden sandals":["tall wooden risers","woven toe thong"],
  "tabi split-toe boots":["split toe front","side hook closure"],
  "woven straw sandals":["plaited straw sole","woven toe cord"],
  "laced ritual sandals":["cord wound lacing","flat woven base"],
  "clawed plate boots":["clawed toe plates","hinged ankle joint"],
  "ridged tall boots":["raised shin ridges","tall stiff shaft"],
  "banded scale boots":["banded scale rows","hooked side closure"],
  "heavy talon boots":["heavy talon caps","broad stable base"],
  "clawed heeled boots":["clawed toe tips","tall slim heel"],
  "buckled tall boots":["rows of shaft buckles","stiff tall shaft"],
  "pointed dark boots":["sharp pointed toe","slim close shaft"],
  "spiked ankle boots":["studded ankle band","short stacked heel"],
  "thick straw sandals":["thick plaited sole","broad toe cords"],
  "heavy wooden clogs":["solid carved block","open heel back"],
  "wrapped cloth boots":["wound cloth strips","tied ankle knot"],
  "banded leather sandals":["wide leather bands","flat hide sole"],
  "strapped gilt sandals":["gilt strap bands","thin flat sole"],
  "soft draped slippers":["soft draped upper","open heel back"],
  "banded ceremonial sandals":["narrow banded straps","gilt edge trim"],
  "tall gilt boots":["gilt banded shaft","squared low heel"],
  "cracked burial boots":["deeply cracked leather","split worn sole"],
  "bandage wrapped boots":["wound linen strips","loose trailing ends"],
  "worn grave shoes":["earth stained upper","worn down tread"],
  "tattered laced boots":["broken lace ends","torn shaft edges"],
  "wrapped ankle cords":["fine wound cords","bare thin sole"],
  "soft floating slippers":["weightless soft upper","barely touching sole"],
  "sheer banded sandals":["translucent bands","thin flat base"],
  "thin strapped shoes":["fine thin straps","low quiet sole"],
  "webbed strap sandals":["webbed strap panels","flat grip sole"],
  "finned ankle boots":["finned ankle edges","smooth wet finish"],
  "banded shell sandals":["set shell bands","woven cord base"],
  "soft wrapped sea boots":["wound damp wraps","soft folded top"],
  "taloned strap sandals":["talon toe caps","open strap upper"],
  "light banded boots":["narrow banded shaft","weightless thin build"],
  "feather cuffed boots":["feather cuff tops","soft light shaft"],
  "short plumed shoes":["plume trimmed edge","low quiet sole"],
  "woven root sandals":["plaited root sole","open toe front"],
  "moss lined boots":["soft moss lining","earth stained shaft"],
  "bark banded shoes":["banded bark strips","fibrous stitched sole"],
  "vine wrapped sandals":["wound vine cords","flat woven base"],
  "heavy stone boots":["solid stone body","chipped rough edges"],
  "carved slab sandals":["carved slab sole","bound cord straps"],
  "banded ore boots":["banded ore strips","broad heavy base"],
  "thick plated shoes":["thick plate toe","squared solid heel"],
  "fuzzy cuffed boots":["fuzzy cuff tops","soft plush shaft"],
  "soft velvet shoes":["deep velvet nap","low rounded toe"],
  "banded plush boots":["banded plush rows","soft padded sole"],
  "powdered strap sandals":["fine powder finish","soft banded straps"],
  "glossy soft boots":["high gloss surface","yielding soft shaft"],
  "translucent strap sandals":["see-through straps","thin flat base"],
  "banded gel shoes":["banded gel strips","smooth quiet sole"],
  "rounded jelly boots":["rounded soft shape","glossy wet finish"],
  "tall slim elven boots":["tall narrow shaft","fine stitched seams"],
  "soft laced boots":["fine cord lacing","soft folded cuff"],
  "banded woven sandals":["narrow woven bands","thin flat sole"],
  "pointed slim shoes":["sharp pointed toe","low slim heel"]
};

// itemDetails is keyed by garment strings; warn in console if a label edit breaks a link.
Object.values(styles).forEach(style=>["tops","bottoms","shoes"].forEach(cat=>style[cat].forEach(item=>{
  if(!itemDetails[item]) console.warn("[data] itemDetails missing:",item);
})));

// The habitat gives the outfit its materials. Not decoration - what the place provides.
const environments={
  forest:["woven leaf and bark materials","layered natural drape"],
  snow:["thick fur and hide materials","bulky insulated proportions"],
  deep:["shell and coral materials","smooth flowing proportions"],
  ember:["scorched hide and ash materials","sharp cracked silhouette"],
  ruin:["scavenged cloth and bone materials","uneven tattered silhouette"]
};

// Head gear the habitat itself calls for. Bestiary has none: a species carries
// its ears and horns regardless of where it lives.
const environmentHero=null;

// Identity only - Korean labels live in app.js settingTranslations, keyed by these ids.
const customEnvironmentNames=["cavern","canopy","marsh","dune","reef","tundra","orchard","hollow","cliff","mire"];
// OTHER-only schema. Similar ornaments stay distinct when their placement or role differs.
// `needsBack` / `needsHero` keep an ornament off a body that has nowhere to put it:
// no wing cuffs without wings, no horn wraps without horns.
const shuffleAddOns=[
  {id:"boneCharms",tag:"carved bone charms on a cord",role:"neck"},
  {id:"clawTips",tag:"metal caps on the fingertips",role:"hands"},
  {id:"tailRing",tag:"banded rings along the tail",role:"tail",needsBack:["tail","tails","scaled"]},
  {id:"hornWraps",tag:"cord wrapped around the horns",role:"horns",needsHero:["horns","antlers"]},
  {id:"wingCuffs",tag:"banded cuffs at the wing joints",role:"wings",needsBack:["feather","bat","insect","mothwing"]},
  {id:"scaleTrim",tag:"scale edged trim on the collar",role:"neck"},
  {id:"mossPatches",tag:"living moss patches on the fabric",role:"garment"},
  {id:"glowVeins",tag:"faintly glowing veins in the fabric",role:"lighting"},
  {id:"ankleBells",tag:"small bells around the ankles",role:"feet"},
  {id:"featherTuft",tag:"feather tufts at the elbows",role:"arms"}
];

const legwear=["wound leg wraps","banded thigh cords","layered fur leg warmers","woven ankle cuffs","scaled shin guards","trailing leg ribbons","knotted cord anklets","banded knee wraps","soft draped leg drapes"];
const specials=["faintly glowing markings on the fabric","trailing woven charms","carved bone clasp","drifting loose threads","overgrown creeping vines","iridescent shifting sheen","hanging carved talismans","layered translucent overlays","fine ash dusting","banded ceremonial cords","split hem tail vent","weathered patina on the metal"];
